### ISSUE TITLE
User-friendly simulator that is similar to the Grafana interface 

### ISSUE THREAD

**Issue by taratran** [gcivil-nyu-org/fall2019-cs-gy-6063-team-moonsurvivors#159]
**User story**
As a user, I want a user-friendly simulator that is similar to the Grafana interface so that I will be able to generate data for the dashboard.

**Acceptance criteria**
Given: The user has navigated to the simulator page 

When: The user generates data (pressing the 'generate data' button)  

And: Continuously submits the data

Then: _The data generated will be sensible and indicative of accurate, realistic data_

**Comment by de846** [comment]
The scope of this ticket feels much more like an epic than an individual story.
