### ISSUE TITLE
Created multiple forms for each sensor and submit the data 

### ISSUE THREAD

**Issue by MichaelLally** [gcivil-nyu-org/fall2019-cs-gy-6063-team-moonsurvivors#160]
**User story**
As a user, I can send individual messages from the simulator relating to specific sensors without consideration for other sensors. Messages can be sent in any order, at the users discretion. Messages are not sent in a bundle or as part of one homogenous form.

**Acceptance criteria**
Current message submission logic must be updated to allow messages from specific sensors to be posted individually.

**Definition of Done**
The user can access the simulator page, enter values to a specific sensor, and submit it. Messages can be submitted in any order (i.e. 4 acceleration messages, followed by 20 fuel level messages, without any messages from other sensors)

**Comment by de846** [comment]
We'll have to update the simulator view to include multiple 'forms'.
