### ISSUE TITLE
Grafana dashboard populates with discrete messages

### ISSUE THREAD

**Issue by MichaelLally** [gcivil-nyu-org/fall2019-cs-gy-6063-team-moonsurvivors#161]
**User story**
Grafana interface populates its panels with data from individual messages. This is a change from the current implementation where grafana pulls from specific columns (i.e. Column: wheel_speed_bl) from messages posted that contain the full status of the vehiclen (all sensors) in a single row.

**Acceptance criteria**
Grafana query logic is updated to accommodate the discrete messages sent to the db from the simulator, in the same manner that they will be sent from the vehicle. 

**Definition of Done**
User can view data from discrete messages in grafana panels.

**Comment by de846** [comment]
All of the panels on the Prod dashboard have been updated to pull data from the tables that represent the new sensors.
