### ISSUE TITLE
Create Blank Top Banner

### ISSUE THREAD

**Issue by MichaelLally** [gcivil-nyu-org/fall2019-cs-gy-6063-team-moonsurvivors#218]
Create a blank html template for the top banner to be used on other pages in the app. This html template will later be integrated to the top of each page's screen on the website (doesn't need to be done as part of this issue). Buttons and navigation will be addd in #217 and It will be added (included) on other pages in #216.

**Comment by RajeevReddyIlavala** [comment]
Pull request #235
