### ISSUE TITLE
Grafana Light Theme

### ISSUE THREAD

**Issue by MichaelLally** [gcivil-nyu-org/fall2019-cs-gy-6063-team-moonsurvivors#223]
User feedback states that our visuals are too hard to see, which will likely be true especially on monitors used outdoors.

The user story is to enable the light theme for our visualizations on grafana by default.

**Comment by de846** [comment]
I changed the `moonadmin` user theme to light. I also ran `heroku config:set -a nyu-mercury-grafana GF_USERS_DEFAULT_THEME="light"` which will set all future user theme's to light by default.
