### ISSUE TITLE
Dashboard does not update 

### ISSUE THREAD

**Issue by gcivil-nyu** [gcivil-nyu-org/fall2019-cs-gy-6063-team-moonsurvivors#252]
Login to the simulator and to the graphana dashboard
Started the simulator
**Observer dashboard not updating at all.** Initially assumed there was a bug

Had to hunt around to find refresh button on the top right and set the default to be 5 seconds update
## Expected Behavior
The application needs to provide sensible defaults so the user is not confused

## Current Behavior
Current behavior forces the user to a) think there is an issue and b) hunt around to change the defaults

## Ideas for Improvement
The application needs to provide sensible defaults so the user is not confused

**Comment by de846** [comment]
Thanks for reporting. This was working previously, but we lost this "feature" when our URL changed. I opened #254 to resolve.
