### ISSUE TITLE
DEBUG = True

### ISSUE THREAD

**Issue by daisycrego** [gcivil-nyu-org/fall2019-cs-gy-6063-team-moonsurvivors#257]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Expected Behavior
When a user attempts to access a garbage url (e.g. http://nyu-mercury-prod.herokuapp.com/;lajvfv), they should see some kind of 404/403 page. 

## Current Behavior
When a user attempts to access a garbage url (e.g. http://nyu-mercury-prod.herokuapp.com/;lajvfv), they see a stack trace.

## Ideas for Improvement
Set DEBUG=False, manage static files using S3 or a similar method if necessary (since Django will no longer manage your static files with DEBUG=False)

## Steps to Reproduce
1. Go to http://nyu-mercury-prod.herokuapp.com/;lajvfv

**Comment by de846** [comment]
Thanks for the feedback! I modified our app so that we don't have DEBUG enabled when running in Heroku, and I appreciate the heads-up about the staticfiles management.
