### ISSUE TITLE
Telemetry Data Simulator- Confusing/ Need to make it user friendly

### ISSUE THREAD

**Issue by Ayushi-0903** [gcivil-nyu-org/fall2019-cs-gy-6063-team-moonsurvivors#265]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

It was little difficult to figure out what's happening or if something is happening or not. When Telemetry Data Simulator started and I didn't get to know. I am uploading the screenshot:
<img width="1440" alt="Screen Shot 2019-11-26 at 8 39 01 PM" src="https://user-images.githubusercontent.com/55497835/69737370-498ff780-1102-11ea-83fa-03b083d44c0d.png">

## Expected Behavior
They should show the user that Telemetry Data Simulator has started or they should update the user clearly.

## Current Behavior
I didn't get to know what's happening. Need to make site more user friendly.

## Ideas for Improvement
Need to make it more user friendly. You should display that Telemetry Data Simulator has been started.

**Comment by de846** [comment]
Hi @Ayushi-0903 - do you have the original image you meant to post? I assume you meant to post a different one. Thanks!

**Comment by de846** [comment]
Thanks for updating. It sounds like the values updating in the fields isn't very intuitive. Thanks for your suggestion. Maybe we should put an indicator at the top as to whether the continuous submission is active or not active.
